### ISSUE TITLE
v0.2 & v1.0 milestones

### ISSUE THREAD

**Issue by the6p4c** [The6P4C/srec#2]
# v0.2 milestones
- [x] Add aliases:
    - `reader::read_records -> crate::read_records`
    - `reader::Error -> crate::ReaderError`
    - `writer::generate_srec_file -> crate::generate_srec_file`
- [x] Improve reader example to show matching on records, reading from `Data` struct
- [x] Implement `Into<u32>` for address structs

# v1.0 milestones
- [ ] Make aliases in crate root the public API, un-`pub` modules
- [ ] Store S0 record data as a vector of bytes, not a string (see https://github.com/ehaskins/srec/commit/a0fe1bd6a9b9d19af3f01ffb743c45f1accc5b9e)
- [ ] Restrict `Address24` and `Count24` to 24 bits
- [ ] Improve return type of `read_records` to be more palatable (e.g. `Reader`)
- [ ] Improve reader error reporting
    - [ ] Include line number in error (`enum Error` -> `struct Error` + `enum ErrorType`)
    - [ ] Include character in unexpected character error
    - [ ] Store expected and actual checksum in invalid checksum error
- [ ] Consider renaming `generate_srec_file`
- [ ] Document + expose `Record::encode` and `FromStr for Record`
- [ ] Allow customisation of line endings in `generate_srec_file`
